require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecentEventsController do

  # This should return the minimal set of attributes required to create a valid
  # RecentEvent. As you add validations to RecentEvent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecentEventsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all recent_events as @recent_events" do
      recent_event = RecentEvent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recent_events).should eq([recent_event])
    end
  end

  describe "GET show" do
    it "assigns the requested recent_event as @recent_event" do
      recent_event = RecentEvent.create! valid_attributes
      get :show, {:id => recent_event.to_param}, valid_session
      assigns(:recent_event).should eq(recent_event)
    end
  end

  describe "GET new" do
    it "assigns a new recent_event as @recent_event" do
      get :new, {}, valid_session
      assigns(:recent_event).should be_a_new(RecentEvent)
    end
  end

  describe "GET edit" do
    it "assigns the requested recent_event as @recent_event" do
      recent_event = RecentEvent.create! valid_attributes
      get :edit, {:id => recent_event.to_param}, valid_session
      assigns(:recent_event).should eq(recent_event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RecentEvent" do
        expect {
          post :create, {:recent_event => valid_attributes}, valid_session
        }.to change(RecentEvent, :count).by(1)
      end

      it "assigns a newly created recent_event as @recent_event" do
        post :create, {:recent_event => valid_attributes}, valid_session
        assigns(:recent_event).should be_a(RecentEvent)
        assigns(:recent_event).should be_persisted
      end

      it "redirects to the created recent_event" do
        post :create, {:recent_event => valid_attributes}, valid_session
        response.should redirect_to(RecentEvent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recent_event as @recent_event" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecentEvent.any_instance.stub(:save).and_return(false)
        post :create, {:recent_event => {}}, valid_session
        assigns(:recent_event).should be_a_new(RecentEvent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecentEvent.any_instance.stub(:save).and_return(false)
        post :create, {:recent_event => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recent_event" do
        recent_event = RecentEvent.create! valid_attributes
        # Assuming there are no other recent_events in the database, this
        # specifies that the RecentEvent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RecentEvent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => recent_event.to_param, :recent_event => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested recent_event as @recent_event" do
        recent_event = RecentEvent.create! valid_attributes
        put :update, {:id => recent_event.to_param, :recent_event => valid_attributes}, valid_session
        assigns(:recent_event).should eq(recent_event)
      end

      it "redirects to the recent_event" do
        recent_event = RecentEvent.create! valid_attributes
        put :update, {:id => recent_event.to_param, :recent_event => valid_attributes}, valid_session
        response.should redirect_to(recent_event)
      end
    end

    describe "with invalid params" do
      it "assigns the recent_event as @recent_event" do
        recent_event = RecentEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecentEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => recent_event.to_param, :recent_event => {}}, valid_session
        assigns(:recent_event).should eq(recent_event)
      end

      it "re-renders the 'edit' template" do
        recent_event = RecentEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecentEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => recent_event.to_param, :recent_event => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recent_event" do
      recent_event = RecentEvent.create! valid_attributes
      expect {
        delete :destroy, {:id => recent_event.to_param}, valid_session
      }.to change(RecentEvent, :count).by(-1)
    end

    it "redirects to the recent_events list" do
      recent_event = RecentEvent.create! valid_attributes
      delete :destroy, {:id => recent_event.to_param}, valid_session
      response.should redirect_to(recent_events_url)
    end
  end

end
