require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UpcomingEventsController do

  # This should return the minimal set of attributes required to create a valid
  # UpcomingEvent. As you add validations to UpcomingEvent, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UpcomingEventsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all upcoming_events as @upcoming_events" do
      upcoming_event = UpcomingEvent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:upcoming_events).should eq([upcoming_event])
    end
  end

  describe "GET show" do
    it "assigns the requested upcoming_event as @upcoming_event" do
      upcoming_event = UpcomingEvent.create! valid_attributes
      get :show, {:id => upcoming_event.to_param}, valid_session
      assigns(:upcoming_event).should eq(upcoming_event)
    end
  end

  describe "GET new" do
    it "assigns a new upcoming_event as @upcoming_event" do
      get :new, {}, valid_session
      assigns(:upcoming_event).should be_a_new(UpcomingEvent)
    end
  end

  describe "GET edit" do
    it "assigns the requested upcoming_event as @upcoming_event" do
      upcoming_event = UpcomingEvent.create! valid_attributes
      get :edit, {:id => upcoming_event.to_param}, valid_session
      assigns(:upcoming_event).should eq(upcoming_event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UpcomingEvent" do
        expect {
          post :create, {:upcoming_event => valid_attributes}, valid_session
        }.to change(UpcomingEvent, :count).by(1)
      end

      it "assigns a newly created upcoming_event as @upcoming_event" do
        post :create, {:upcoming_event => valid_attributes}, valid_session
        assigns(:upcoming_event).should be_a(UpcomingEvent)
        assigns(:upcoming_event).should be_persisted
      end

      it "redirects to the created upcoming_event" do
        post :create, {:upcoming_event => valid_attributes}, valid_session
        response.should redirect_to(UpcomingEvent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved upcoming_event as @upcoming_event" do
        # Trigger the behavior that occurs when invalid params are submitted
        UpcomingEvent.any_instance.stub(:save).and_return(false)
        post :create, {:upcoming_event => {}}, valid_session
        assigns(:upcoming_event).should be_a_new(UpcomingEvent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UpcomingEvent.any_instance.stub(:save).and_return(false)
        post :create, {:upcoming_event => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested upcoming_event" do
        upcoming_event = UpcomingEvent.create! valid_attributes
        # Assuming there are no other upcoming_events in the database, this
        # specifies that the UpcomingEvent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UpcomingEvent.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => upcoming_event.to_param, :upcoming_event => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested upcoming_event as @upcoming_event" do
        upcoming_event = UpcomingEvent.create! valid_attributes
        put :update, {:id => upcoming_event.to_param, :upcoming_event => valid_attributes}, valid_session
        assigns(:upcoming_event).should eq(upcoming_event)
      end

      it "redirects to the upcoming_event" do
        upcoming_event = UpcomingEvent.create! valid_attributes
        put :update, {:id => upcoming_event.to_param, :upcoming_event => valid_attributes}, valid_session
        response.should redirect_to(upcoming_event)
      end
    end

    describe "with invalid params" do
      it "assigns the upcoming_event as @upcoming_event" do
        upcoming_event = UpcomingEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UpcomingEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => upcoming_event.to_param, :upcoming_event => {}}, valid_session
        assigns(:upcoming_event).should eq(upcoming_event)
      end

      it "re-renders the 'edit' template" do
        upcoming_event = UpcomingEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UpcomingEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => upcoming_event.to_param, :upcoming_event => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested upcoming_event" do
      upcoming_event = UpcomingEvent.create! valid_attributes
      expect {
        delete :destroy, {:id => upcoming_event.to_param}, valid_session
      }.to change(UpcomingEvent, :count).by(-1)
    end

    it "redirects to the upcoming_events list" do
      upcoming_event = UpcomingEvent.create! valid_attributes
      delete :destroy, {:id => upcoming_event.to_param}, valid_session
      response.should redirect_to(upcoming_events_url)
    end
  end

end
